export const GET_PICTURE = 'GET_PICTURE';
export const GET_PICTURE_REQUEST = 'GET_PICTURE_REQUEST';
export const GET_PICTURE_SUCCESS = 'GET_PICTURE_SUCCESS';
export const GET_PICTURE_FAIL = 'GET_PICTURE_FAIL';
export const REMOVE_HISTORY_ITEM = 'REMOVE_HISTORY_ITEM';

